### ISSUE TITLE
File/module Image_preparation not found

### ISSUE THREAD

**Issue by ZouaghiHoussem** [YashGunjal/asm#2]
Hello, could you please let me know where I can find the Image_preparation file or Module ?

**Comment by Miaoing** [comment]
same here

**Comment by sarzvnska** [comment]
same problem, its a shame - code looks good

**Comment by YashGunjal** [comment]
I am not aware, this repo is a fork from  https://github.com/andrewrch/active_shape_models . 
I also faced the same issue.
